services:
  - type: web
    name: permitvista-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # Render will use Dockerfile automatically when env: docker is set
    # Or if Dockerfile is detected in root, Render will use it automatically

